import type { Metadata } from "next";
import { Link, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";

import "./globals.css";
import style from "./layout.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <Theme appearance="dark" asChild>
        <body className={style.body}>

          <header className={style.header}>
            <Link href="/">
              <h1>Pitch Share</h1>
            </Link>
            <p>Baseball pitching session analysis and tracking</p>
          </header>

          <div className={style.main}>
            {children}
          </div>
        </body>
      </Theme>
    </html>
  );
}
